# Generated by Django 5.0.2 on 2024-03-15 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
        ("restricted_area", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restrictedareadata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restricted_area_data",
                to="login.login",
            ),
        ),
    ]
